# Generated by Django 5.0.7 on 2024-08-24 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_itemestoque_cor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenspedido',
            old_name='itemes_toque',
            new_name='item_estoque',
        ),
    ]
